# Schema for the configuration files of the simplepodcast module.

simplepodcast.settings:
  type: config_object
  label: 'SimplePodcast settings'
  mapping:
    episode_content_type:
      type: string
      label: 'Episode Content Type'
    rss_path_name:
      type: string
      label: 'Path of SimplePodcast Feed'
    title:
      type: string
      label: 'Podcast Title'
    description:
      type: string
      label: 'Podcast Description'
    language:
      type: string
      label: 'Podcast Language'
    copyright:
      type: string
      label: 'Podcast Copyright'
    explicit:
      type: boolean
      label: 'Podcast Explicit'
    owner_name:
      type: string
      label: 'iTunes Owner Name'
    owner_author:
      type: string
      label: 'iTunes Author Name'
    channel_image:
      type: string
      label: 'Podcast Channel Image'
    owner_email:
      type: email
      label: 'iTunes Owner email address'
    category_1:
      type: string
      label: 'iTunes Podcast Category 1'
    category_2:
      type: string
      label: 'iTunes Podcast Category 2'
    category_3:
      type: string
      label: 'iTunes Podcast Category 3'
    item_title:
      type: string
      label: 'Episode Title'
    item_author:
      type: string
      label: 'Episode Author'
    item_subtitle:
      type: string
      label: 'Episode Sub-Title'
    item_summary:
      type: string
      label: 'Episode Summary'
    item_image:
      type: string
      label: 'Episode Image'
    item_media:
      type: string
      label: 'Episode Media'
    item_media_length:
      type: string
      label: 'Episode Media Length'
    item_media_duration:
      type: string
      label: 'Episode Media Duration'