# Schema for the configuration files of the ga_push module.
ga_push.settings:
  type: config_object
  label: 'GA Push settings'
  mapping:
    default_method:
      type: string
      label: 'Default method'
