id: d7_ga_push_settings
label: GA Push 7 configuration
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - ga_push_default_method
process:
  default_method: ga_push_default_method
destination:
  plugin: config
  config_name: ga_push.settings
