name: Configuration Rewrite
type: module
description: Rewrites existing configuration on module installation via using a "rewrite" folder in the config directory.
core: 8.x
package: Configuration

# Information added by Drupal.org packaging script on 2019-10-22
version: '8.x-1.2'
project: 'config_rewrite'
datestamp: 1571761993
