action.configuration.bibcite_entity_contributor_delete:
  type: action_configuration_default

action.configuration.bibcite_entity_contributor_save:
  type: action_configuration_default

action.configuration.bibcite_entity_keyword_delete:
  type: action_configuration_default

action.configuration.bibcite_entity_keyword_save:
  type: action_configuration_default

action.configuration.bibcite_entity_reference_delete:
  type: action_configuration_default

action.configuration.bibcite_entity_reference_save:
  type: action_configuration_default

action.configuration.bibcite_entity_keyword_merge:
  type: action_configuration_default

action.configuration.bibcite_entity_contributor_merge:
  type: action_configuration_default

bibcite_entity.link:
  type: mapping
  mapping:
    enabled:
      type: boolean
    weight:
      type: integer

field.formatter.settings.bibcite_contributor_label:
  type: mapping
  label: 'Label'
  mapping:
    role:
      type: bool
      label: 'Show role'
    category:
      type: bool
      label: 'Show category'
