bibcite_entity.bibcite_reference_type.*:
  type: config_entity
  label: 'Reference type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    override:
      type: boolean
      label: 'Override default properties'
    fields:
      type: sequence
      label: 'Fields'
      sequence:
        type: mapping
        label: 'Field'
        mapping:
          visible:
            type: boolean
            label: 'Visible'
          required:
            type: boolean
            label: 'Required'
          label:
            type: label
            label: 'Label'
          hint:
            type: text
            label: 'Hint'
    uuid:
      type: string
