field.formatter.settings.bibcite_contributor_label:
  type: mapping
  label: 'Author reference label display format settings'
  mapping:
    link:
      type: boolean
      label: 'Link label to the referenced author'
