id: d7_ga_push_form_validate_settings
label: GA Push Form Validate 7 configuration
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - ga_push_form_validate_forms
    - ga_push_form_validate_show_form_ids
process:
  form_list: ga_push_form_validate_forms
  show_form_ids: ga_push_form_validate_show_form_ids
destination:
  plugin: config
  config_name: ga_push_form_validate.settings
