# Schema for the configuration files of the ga_push_form_validate module.
ga_push_form_validate.settings:
  type: config_object
  label: 'GA Push Form Validate settings'
  mapping:
    form_list:
      type: string
      label: 'Validate form list'
    show_form_ids:
      type: boolean
      label: 'Show form ids'
